const tasks = [
    {
        name: 'Search page mockup',
        dev: ['Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock'],
        type: ['Programming', 'Meetings', 'Graphic Design', 'Markup', 'Estimation'],
        status: 'Completed',
        estimation: 0.0,
        totalTime: 232.17,
        periodTime: 23.00,
        efficiency: '100%',
    },
    {
        name: 'Two levels of the menu mockup',
        dev: ['Robert Fox'],
        type: ['Graphic Design'],
        status: 'Non Completed',
        estimation: 0.0,
        totalTime: 1567.60,
        periodTime: 15.00,
        efficiency: '-',
    },
    {
        name: 'Edit pictures',
        dev: ['Dianne Russel', 'Adam Gordon', 'Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock'],
        type: ['Graphic Design'],
        status: 'Non Completed',
        estimation: 0.0,
        totalTime: 678.20,
        periodTime: 67.00,
        efficiency: '-',
    },
    {
        name: 'Subdomain home pages mockup',
        dev: ['Diane Russel'],
        type: ['Graphic Design'],
        status: 'Non Completed',
        estimation: 0.0,
        totalTime: 756.70,
        periodTime: 75.00,
        efficiency: '-',
    },
    {
        name: 'Landing page mockup',
        dev: ['Diane Russel'],
        type: ['Graphic Design'],
        status: 'Non Completed',
        estimation: 0.0,
        totalTime: 345.60,
        periodTime: 45.00,
        efficiency: '-',
    },
    {
        name: 'Search page mockup',
        dev: ['Courtney Henry', 'Kent Peacock', 'Adam Gordon', 'Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock'],
        type: ['Programming', 'Meetings', 'Graphic Design', 'Markup', 'Estimation'],
        status: 'Completed',
        estimation: 0.0,
        totalTime: 232.17,
        periodTime: 23.00,
        efficiency: '100%',
    },
    {
        name: 'Landing page mockup',
        dev: ['Courtney Henry', 'Augusta Walter'],
        type: ['Graphic Design'],
        status: 'Non Completed',
        estimation: 0.0,
        totalTime: 345.60,
        periodTime: 45.00,
        efficiency: '-',
    },
    {
        name: 'Search page mockup',
        dev: ['Courtney Henry', 'Kent Peacock'],
        type: ['Programming', 'Meetings', 'Graphic Design', 'Markup', 'Estimation'],
        status: 'Completed',
        estimation: 0.0,
        totalTime: 232.17,
        periodTime: 23.00,
        efficiency: '100%',
    },
    {
        name: 'Search page mockup',
        dev: ['Courtney Henry', 'Kent Peacock', 'Adam Gordon', 'Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock'],
        type: ['Programming', 'Meetings', 'Graphic Design', 'Markup', 'Estimation'],
        status: 'Completed',
        estimation: 0.0,
        totalTime: 232.17,
        periodTime: 23.00,
        efficiency: '100%',
    },
    {
        name: 'Search page mockup',
        dev: ['Courtney Henry', 'Kent Peacock', 'Adam Gordon', 'Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock'],
        type: ['Programming', 'Meetings', 'Graphic Design', 'Markup', 'Estimation'],
        status: 'Completed',
        estimation: 0.0,
        totalTime: 232.17,
        periodTime: 23.00,
        efficiency: '100%',
    },


    {
        name: 'Two levels of the menu mockup',
        dev: ['Robert Fox'],
        type: ['Graphic Design'],
        status: 'Non Completed',
        estimation: 0.0,
        totalTime: 1567.60,
        periodTime: 15.00,
        efficiency: '-',
    },

    {
        name: 'Edit pictures',
        dev: ['Dianne Russel', 'Adam Gordon', 'Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock'],
        type: ['Graphic Design'],
        status: 'Non Completed',
        estimation: 0.0,
        totalTime: 678.20,
        periodTime: 67.00,
        efficiency: '-',
    },
    {
        name: 'Search page mockup',
        dev: ['Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock'],
        type: ['Programming', 'Meetings', 'Graphic Design', 'Markup', 'Estimation'],
        status: 'Completed',
        estimation: 0.0,
        totalTime: 232.17,
        periodTime: 23.00,
        efficiency: '100%',
    },

    {
        name: 'Subdomain home pages mockup',
        dev: ['Diane Russel'],
        type: ['Graphic Design'],
        status: 'Non Completed',
        estimation: 0.0,
        totalTime: 756.70,
        periodTime: 75.00,
        efficiency: '-',
    },
    {
        name: 'Landing page mockup',
        dev: ['Diane Russel'],
        type: ['Graphic Design'],
        status: 'Non Completed',
        estimation: 0.0,
        totalTime: 345.60,
        periodTime: 45.00,
        efficiency: '-',
    },
    {
        name: 'Search page mockup',
        dev: ['Courtney Henry', 'Kent Peacock', 'Adam Gordon', 'Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock'],
        type: ['Programming', 'Meetings', 'Graphic Design', 'Markup', 'Estimation'],
        status: 'Completed',
        estimation: 0.0,
        totalTime: 232.17,
        periodTime: 23.00,
        efficiency: '100%',
    },
    {
        name: 'Landing page mockup',
        dev: ['Courtney Henry', 'Augusta Walter'],
        type: ['Graphic Design'],
        status: 'Non Completed',
        estimation: 0.0,
        totalTime: 345.60,
        periodTime: 45.00,
        efficiency: '-',
    },
    {
        name: 'Search page mockup',
        dev: ['Courtney Henry', 'Kent Peacock'],
        type: ['Programming', 'Meetings', 'Graphic Design', 'Markup', 'Estimation'],
        status: 'Completed',
        estimation: 0.0,
        totalTime: 232.17,
        periodTime: 23.00,
        efficiency: '100%',
    },
    {
        name: 'Search page mockup',
        dev: ['Courtney Henry', 'Kent Peacock', 'Adam Gordon', 'Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock'],
        type: ['Programming', 'Meetings', 'Graphic Design', 'Markup', 'Estimation'],
        status: 'Completed',
        estimation: 0.0,
        totalTime: 232.17,
        periodTime: 23.00,
        efficiency: '100%',
    },
    {
        name: 'Search page mockup',
        dev: ['Courtney Henry', 'Kent Peacock', 'Adam Gordon', 'Robert Fox', 'Kent Peacock', 'John Dou', 'Robert Fox', 'Kent Peacock'],
        type: ['Programming', 'Meetings', 'Graphic Design', 'Markup', 'Estimation'],
        status: 'Completed',
        estimation: 0.0,
        totalTime: 232.17,
        periodTime: 23.00,
        efficiency: '100%',
    },
]






